/**
 * Query classification for the growth report.
 *
 * ## Why this exists
 *
 * Search Console attributes impressions to this site for strings like
 * `d'acord`, `check again`, `si`, `las dos cosas` and `para ir mañana`, at
 * positions 2–6, with no clicks ever. Those are not things a person types into
 * a search box; they are consistent with fan-out sub-queries generated by an
 * AI system. They inflate impressions and crush CTR, and through September
 * they grew fast enough to move the site-wide number on their own.
 *
 * So site-wide CTR mixes two populations with different denominators and is
 * not a usable KPI. This module separates them, so a decision can be made
 * against the queries a human actually typed.
 *
 * ## The rule this file obeys
 *
 * **Nothing is discarded and nothing is bucketed silently.** Every query gets
 * a `kind` and a `reason`, the report prints the reason, and a person can
 * disagree with any single call by reading it. A classifier whose output
 * cannot be audited is worse than no classifier, because it launders a guess
 * into a number.
 *
 * Where a query is genuinely ambiguous — `6 de octubre` could be a fragment or
 * could be somebody asking whether it is a public holiday — it lands in a
 * bucket that says so, rather than being forced into one of the two clean
 * ones.
 *
 * ## Order of checks
 *
 * 1. **Brand.** Our own name, in any spelling.
 * 2. **Topical.** Contains a word from a cluster vocabulary. A topical query
 *    is *always* human, however short: `bolets` is one word and is the most
 *    valuable query on the site.
 * 3. **Noise.** Every token is a confirmation, a deictic, a bare temporal
 *    word or a bare date, and the query is short.
 * 4. **Unclassified.** Everything else. Reported separately and never counted
 *    as qualified, because we do not know what it is.
 */

export type QueryKind = "brand" | "human" | "noise" | "unclassified";

export type ClusterKey =
  | "bolets"
  | "tardor"
  | "gastronomia"
  | "agenda"
  | "sitges"
  | "calendari-laboral"
  | "taxa-turistica"
  | "barcelona-practical"
  | "travel"
  | "destinations";

export interface Classification {
  kind: QueryKind;
  cluster: ClusterKey | null;
  /** Why this call was made, in words, so a person can disagree with it. */
  reason: string;
}

/* -------------------------------------------------------------------------- */
/* Vocabularies                                                               */
/* -------------------------------------------------------------------------- */

/** Lowercase, accents removed, punctuation flattened to spaces. */
export function normalise(query: string): string {
  return query
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const BRAND = [
  "catalunyainfo",
  "catalunya info",
  "catalunya informacio",
  "catalunya informacion",
  "catalunya information",
  "info catalunya",
  "catalunyainfo com",
];

/**
 * Cluster vocabularies, checked in this order.
 *
 * Order matters where a word belongs to more than one subject: `barcelona`
 * appears in the tourist tax queries and in the practical ones, so the tax
 * vocabulary is checked first and wins when its own words are present.
 */
const CLUSTERS: { key: ClusterKey; tokens: string[] }[] = [
  {
    key: "sitges",
    tokens: ["sitges", "film festival", "festival de cinema", "festival de cine"],
  },
  {
    key: "taxa-turistica",
    tokens: [
      "taxa turistica",
      "tasa turistica",
      "tourist tax",
      "impost estades",
      "impuesto estancias",
      "ieet",
      "recarrec",
      "recargo",
    ],
  },
  {
    key: "calendari-laboral",
    tokens: [
      "calendari laboral",
      "calendario laboral",
      "festiu",
      "festius",
      "festivo",
      "festivos",
      "public holiday",
      "public holidays",
      "bank holiday",
      "dia de lliure disposicio",
      "pont",
      "ponts",
      "puente",
      "puentes",
      // Easter surfaced as a cluster of its own in the first report run: five
      // separate 2027 queries, all on page one, none classified. Adding them
      // here is the audit trail doing its job.
      "semana santa",
      "setmana santa",
      "divendres sant",
      "viernes santo",
      "dijous sant",
      "jueves santo",
      "dilluns de pasqua",
      "lunes de pascua",
      "pasqua",
      "pascua",
      "holiday",
      "holidays",
      "fiestas",
      "festes",
      "laboral",
      "laborals",
      "laborales",
    ],
  },
  {
    key: "bolets",
    tokens: [
      "bolet",
      "bolets",
      "seta",
      "setas",
      "rovello",
      "rovellons",
      "niscalo",
      "niscalos",
      "ceps",
      "cep",
      "camagroc",
      "fredolic",
      "moixerno",
      "mushroom",
      "mushrooms",
      "micologic",
      "boletaire",
    ],
  },
  {
    key: "tardor",
    tokens: [
      "tardor",
      "otono",
      "fall colors",
      "fall colours",
      "autumn",
      "foliage",
      "castanyada",
      "castanada",
      "castanyes",
      "castanas",
      "fageda",
      "faig",
      "haya",
      "hayedo",
    ],
  },
  {
    key: "gastronomia",
    tokens: [
      "fira gastronomica",
      "fires gastronomiques",
      "feria gastronomica",
      "ferias gastronomicas",
      "food festival",
      "food fair",
      "formatge",
      "queso",
      "vi novell",
      "calcotada",
    ],
  },
  {
    key: "agenda",
    tokens: [
      "cap de setmana",
      "fin de semana",
      "weekend",
      "que fer",
      "que hacer",
      "things to do",
      "what to do",
      "agenda",
      "festa major",
      "fiesta mayor",
    ],
  },
  {
    key: "barcelona-practical",
    tokens: [
      "barcelona",
      "aeroport",
      "aeropuerto",
      "airport",
      "el prat",
      "aerobus",
      "t casual",
      "tcasual",
      "hola barcelona",
      "metro",
      "rodalies",
      "cercanias",
    ],
  },
  {
    key: "travel",
    tokens: [
      "tren",
      "train",
      "escapada",
      "escapades",
      "escapadas",
      "day trip",
      "day trips",
      "excursio",
      "excursion",
      "sense cotxe",
      "sin coche",
      "without a car",
    ],
  },
  {
    key: "destinations",
    tokens: [
      "poble",
      "pobles",
      "pueblo",
      "pueblos",
      "village",
      "villages",
      "medieval",
      "gaudi",
      "montserrat",
      "lloc",
      "llocs",
      "lugar",
      "lugares",
      "girona",
      "tarragona",
      "lleida",
      "costa brava",
      "pirineu",
      "pirineus",
      "pirineos",
      "ripolles",
      "cerdanya",
      "bergueda",
      "setcases",
      "vall d en bas",
      "vall den bas",
      "garrotxa",
      "alt urgell",
      "val d aran",
      "mollo",
    ],
  },
];

/**
 * Tokens that carry no search intent on their own.
 *
 * A query made entirely of these is a fragment. Any one of them next to a
 * topical word is fine and stays human — `bolets avui` is a real question.
 */
const CONFIRMATION = [
  "si",
  "no",
  "ok",
  "okay",
  "vale",
  "d acord",
  "dacord",
  "acord",
  "exacte",
  "exacto",
  "correcto",
  "correcte",
  "bueno",
  "perfecto",
  "perfecte",
  "gracias",
  "gracies",
  "thanks",
  "thank you",
  "check again",
  "again",
  "de acuerdo",
  "entesos",
  "clar",
];

const TEMPORAL = [
  "avui",
  "hoy",
  "today",
  "dema",
  "manana",
  "tomorrow",
  "ahir",
  "ayer",
  "yesterday",
  "ara",
  "ahora",
  "now",
  "aquesta setmana",
  "esta semana",
  "this week",
  "aquest mes",
  "este mes",
  "this month",
  "a fecha de hoy",
  "por ahora",
  "de moment",
  "setmana",
  "semana",
  "week",
  "mes",
  "month",
];

const DEICTIC = [
  "las dos cosas",
  "les dues coses",
  "los dos",
  "els dos",
  "el mismo",
  "el mateix",
  "aquest",
  "aquesta",
  "este",
  "esta",
  "eso",
  "aixo",
  "that",
  "it",
  "the",
  "la",
  "el",
  "els",
  "les",
  "los",
  "de",
  "del",
  "a",
  "en",
  "i",
  "y",
  "and",
  "mas",
  "mes",
  "alguna",
  "algun",
  "alguna foto",
  "foto",
  "cosas",
  "coses",
  "ir",
  "anar",
  "go",
  "para",
  "per",
];

/** Month names, for spotting a query that is only a date. */
const MONTHS = [
  "gener",
  "febrer",
  "marc",
  "abril",
  "maig",
  "juny",
  "juliol",
  "agost",
  "setembre",
  "octubre",
  "novembre",
  "desembre",
  "enero",
  "febrero",
  "marzo",
  "mayo",
  "junio",
  "julio",
  "agosto",
  "septiembre",
  "octubre",
  "noviembre",
  "diciembre",
  "january",
  "february",
  "march",
  "april",
  "may",
  "june",
  "july",
  "august",
  "september",
  "october",
  "november",
  "december",
  "jan",
  "feb",
  "mar",
  "apr",
  "jun",
  "jul",
  "aug",
  "sep",
  "sept",
  "oct",
  "nov",
  "dec",
];

const WEEKDAYS = [
  "dilluns",
  "dimarts",
  "dimecres",
  "dijous",
  "divendres",
  "dissabte",
  "diumenge",
  "lunes",
  "martes",
  "miercoles",
  "jueves",
  "viernes",
  "sabado",
  "domingo",
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
];

/* -------------------------------------------------------------------------- */
/* Classification                                                             */
/* -------------------------------------------------------------------------- */

function containsPhrase(text: string, phrase: string): boolean {
  // Word-boundary match on the normalised string, so `mes` does not match
  // inside `mesos` and `si` does not match inside `sitges`.
  const pattern = new RegExp(`(^|\\s)${phrase.replace(/\s+/g, "\\s+")}($|\\s)`);
  return pattern.test(text);
}

/** The cluster a query belongs to, or null when no vocabulary matches. */
export function clusterFor(query: string): ClusterKey | null {
  const text = normalise(query);
  for (const cluster of CLUSTERS) {
    for (const token of cluster.tokens) {
      if (containsPhrase(text, token)) return cluster.key;
    }
  }
  return null;
}

function isBareDate(text: string): boolean {
  const words = text.split(" ").filter(Boolean);
  if (words.length === 0 || words.length > 4) return false;
  return words.every(
    (word) =>
      /^\d{1,4}$/.test(word) ||
      MONTHS.includes(word) ||
      WEEKDAYS.includes(word) ||
      DEICTIC.includes(word),
  );
}

function allIn(text: string, lists: string[][]): boolean {
  const words = text.split(" ").filter(Boolean);
  if (words.length === 0) return false;
  const flat = lists.flat();
  return words.every((word) => flat.includes(word));
}

export function classifyQuery(query: string): Classification {
  const text = normalise(query);

  if (text.length === 0) {
    return { kind: "unclassified", cluster: null, reason: "empty after normalisation" };
  }

  /* 1. Brand ------------------------------------------------------------- */
  for (const brand of BRAND) {
    if (containsPhrase(text, brand) || text.replace(/\s/g, "") === brand.replace(/\s/g, "")) {
      return { kind: "brand", cluster: null, reason: `brand term "${brand}"` };
    }
  }

  /* 2. Topical ----------------------------------------------------------- */
  const cluster = clusterFor(query);
  if (cluster) {
    return { kind: "human", cluster, reason: `topical: matches the ${cluster} vocabulary` };
  }

  /* 3. Noise ------------------------------------------------------------- */
  const words = text.split(" ").filter(Boolean);

  // Multi-word fixed fragments first, so "las dos cosas" is caught as a phrase.
  for (const phrase of [...CONFIRMATION, ...TEMPORAL, ...DEICTIC].filter((p) => p.includes(" "))) {
    if (text === phrase) {
      return { kind: "noise", cluster: null, reason: `fixed fragment "${phrase}"` };
    }
  }

  if (words.length <= 4 && allIn(text, [CONFIRMATION, TEMPORAL, DEICTIC])) {
    return {
      kind: "noise",
      cluster: null,
      reason: "every word is a confirmation, a deictic or a bare temporal word",
    };
  }

  if (isBareDate(text)) {
    // Ambiguous on purpose: this could be someone asking whether a date is a
    // public holiday. Counted as noise, but the reason says why, and the
    // report prints it so the call can be overruled.
    return { kind: "noise", cluster: null, reason: "bare date with no subject" };
  }

  if (words.length === 1 && words[0] && words[0].length <= 3) {
    return { kind: "noise", cluster: null, reason: "single token of three characters or fewer" };
  }

  /* 4. Unknown ----------------------------------------------------------- */
  return {
    kind: "unclassified",
    cluster: null,
    reason: "no brand, no cluster vocabulary, not a recognised fragment",
  };
}

/* -------------------------------------------------------------------------- */
/* Opportunity score                                                          */
/* -------------------------------------------------------------------------- */

export interface QueryRow {
  query: string;
  clicks: number;
  impressions: number;
  ctr: number;
  position: number;
}

export interface Opportunity {
  score: number;
  /** Every term that went into the score, so the number can be argued with. */
  terms: string[];
}

/**
 * How much a query is worth going after, on a scale nobody should treat as
 * precise.
 *
 * Deliberately a handful of additions rather than a model: the inputs are
 * three numbers and a label, and anything more elaborate would imply a
 * confidence the data does not support. No search-volume estimate is invented;
 * impressions are the only volume signal used, because they are the only one
 * measured.
 */
export function opportunityScore(row: QueryRow, classification: Classification): Opportunity {
  const terms: string[] = [];
  let score = 0;

  if (classification.kind !== "human") {
    return {
      score: 0,
      terms: [`not a human query (${classification.kind}) — no opportunity claimed`],
    };
  }

  score += 3;
  terms.push("+3 human query with clear intent");

  const volume = Math.min(row.impressions / 10, 4);
  score += volume;
  terms.push(`+${volume.toFixed(1)} volume (${row.impressions} impressions, capped at 4)`);

  if (row.position >= 5 && row.position <= 20) {
    score += 3;
    terms.push(`+3 position ${row.position.toFixed(1)}: close enough to move`);
  } else if (row.position > 20 && row.position <= 40) {
    score += 1.5;
    terms.push(`+1.5 position ${row.position.toFixed(1)}: reachable with a dedicated page`);
  } else if (row.position > 40) {
    score += 0.5;
    terms.push(`+0.5 position ${row.position.toFixed(1)}: only worth it with new content`);
  } else if (row.position <= 3) {
    score -= 4;
    terms.push(`-4 position ${row.position.toFixed(1)}: already won, nothing to gain`);
  } else {
    terms.push(`+0 position ${row.position.toFixed(1)}`);
  }

  // A query with words beyond its cluster term is asking something specific
  // that a general page answers badly. That is where a new page can win
  // without competing with the one we already rank with.
  const words = normalise(row.query).split(" ").filter(Boolean);
  if (words.length >= 3) {
    score += 2;
    terms.push("+2 specific phrasing: a general page answers it poorly");
  }

  if (row.clicks === 0 && row.impressions >= 10) {
    score += 1;
    terms.push("+1 impressions but no clicks: visible and not chosen");
  }

  return { score: Math.round(score * 10) / 10, terms };
}
