import "server-only";

import type { Block } from "@/lib/content/blocks";
import { LOCALES, type Locale } from "@/lib/i18n/config";
import { publishArticle, type ArticleSpec, type PublishResult } from "@/lib/content/publish-article";
import { IMAGE_BY_KEY } from "@/lib/content/images";
import { relatedBlocks } from "@/lib/content/features/shared";
import { zoneHref, zonesFor } from "@/lib/content/mushroom-zones/registry";
import { LEVEL_RULE, READ_AT, SOURCE, WINDOW_DAYS, ZONE_READINGS } from "./conditions";
import { COPY, HERO, LEVEL_LABEL, LIVE_COPY, SOURCES, ZONES } from "./payload";

/**
 * The mycological conditions report.
 *
 * Its measured layer is refreshed from Meteocat by `npm run mushrooms:refresh`
 * and stamped with the date it was read. Five other pages on this site call
 * this a *weekly* report; between 13 September and 7 October it was refreshed
 * once, and it went from 25 clicks a week at position 2.8 to zero during the
 * peak of the season. `tests/mushroom-freshness.test.ts` now fails the build
 * when the data is more than ten days old, because a warning in a log is
 * exactly what those three weeks already were.
 *
 * Evergreen URLs: this same entry is refreshed each week during the season with
 * new rainfall figures and a new ranking, so the page accumulates history
 * rather than scattering it across dated URLs.
 */

export const ENTRY_KEY = "mushroom-conditions-catalunya";

const PUBLISHED = new Date("2026-09-13T17:30:00+02:00");
// Not a constant: the page is only as fresh as the data behind it, so the
// stamp the reader sees is the date the rainfall was actually read.
const LAST_VERIFIED = new Date(`${READ_AT}T12:00:00+02:00`);

/** Heading for the local-zone list, used only once a zone exists. */
const ZONES_HEADING: Record<Locale, string> = {
  ca: "Per zones",
  es: "Por zonas",
  en: "By area",
};

/**
 * The measured layer.
 *
 * Everything in `conditions.ts` is generated by `npm run mushrooms:refresh`
 * from Meteocat's open data and carries the date it was read. This is the part
 * of the page that has to be current: the prose below it describes the season
 * and ages gracefully, the rainfall does not.
 *
 * The five editorial bands collapse into the three the `conditionsMap` block
 * allows, because that block's vocabulary is deliberately closed and none of
 * its values can be read as "there are mushrooms here".
 */
const LIVE: Record<Locale, {
  title: string;
  intro: string;
  rule: string;
  background: string;
  legendFav: string;
  legendMod: string;
  legendLim: string;
  legendUnknown: string;
  note: string;
}> = LIVE_COPY;

function bandFor(level: string): "favourable" | "moderate" | "limiting" {
  if (level === "very" || level === "favourable") return "favourable";
  if (level === "interesting" || level === "patchy") return "moderate";
  return "limiting";
}

function conditionsBlock(locale: Locale): Block {
  const copy = LIVE[locale];
  const threshold = (name: string) =>
    String(LEVEL_RULE.find((rule) => rule.level === name)?.minMm ?? "");

  return {
    type: "conditionsMap",
    title: copy.title.replace("{days}", String(WINDOW_DAYS)),
    intro: copy.intro.replace("{date}", READ_AT),
    legend: [
      { level: "favourable", label: copy.legendFav },
      { level: "moderate", label: copy.legendMod },
      { level: "limiting", label: copy.legendLim },
    ],
    areas: ZONE_READINGS.map((reading) => {
      const zone = ZONES.find((item) => item.id === reading.id);
      return {
        name: zone ? zone.name[locale] : reading.id,
        level: bandFor(reading.level),
        note:
          `${reading.mm} mm \u2014 ` +
          copy.note
            .replace("{stations}", String(reading.stations))
            .replace("{days}", String(reading.daysSinceRain)),
      };
    }),
    source: { name: SOURCE.name, url: SOURCE.url },
    verifiedAt: READ_AT,
    note: copy.rule
      .replace("{very}", threshold("very"))
      .replace("{fav}", threshold("favourable"))
      .replace("{int}", threshold("interesting")),
  } as Block;
}

export function buildBody(locale: Locale, heroMediaId?: string): Block[] {
  const copy = COPY[locale];
  const blocks: Block[] = [];

  copy.intro.forEach((text, index) => {
    blocks.push({ type: "paragraph", text, ...(index === 0 ? { lead: true } : {}) });
  });

  blocks.push({
    type: "callout",
    tone: "info",
    title: copy.directAnswerTitle,
    text: copy.directAnswer,
  });

  blocks.push({
    type: "keyFacts",
    title: copy.keyFactsTitle,
    items: copy.keyFacts.map((f) => ({ label: f.label, value: f.value })),
  });

  // Today's reading comes before the editorial ranking: somebody who opened
  // this page wants to know what the ground is like now, not how the season
  // has gone.
  blocks.push(conditionsBlock(locale));
  blocks.push({ type: "paragraph", text: LIVE[locale].background });

  // The condition ranking. A table rather than a bespoke component: it stacks
  // into cards on a phone, reads correctly in a screen reader, and is the same
  // structure in all three languages.
  blocks.push({
    type: "table",
    caption: copy.tableCaption,
    headers: copy.tableHeaders,
    rows: ZONES.map((zone) => [
      zone.name[locale],
      LEVEL_LABEL[zone.level][locale],
      zone.figure[locale],
      zone.reading[locale],
    ]),
  });

  // Stated immediately under the ranking, where someone might otherwise read a
  // rating as an observation of mushrooms.
  blocks.push({
    type: "callout",
    tone: "warning",
    title: copy.ratingDisclaimerTitle,
    text: copy.ratingDisclaimer,
  });

  if (heroMediaId) {
    blocks.push({ type: "image", mediaId: heroMediaId, size: "wide" });
  }

  blocks.push({ type: "heading", level: 2, text: copy.lateHeading });
  for (const text of copy.late) blocks.push({ type: "paragraph", text });

  for (const zone of ZONES) {
    blocks.push({ type: "heading", level: 2, text: zone.heading[locale] });
    blocks.push({
      type: "paragraph",
      text: `**${LEVEL_LABEL[zone.level][locale]}.**`,
    });
    for (const text of zone.body[locale]) blocks.push({ type: "paragraph", text });
  }

  blocks.push({ type: "heading", level: 2, text: copy.whyHeading });
  for (const text of copy.why) blocks.push({ type: "paragraph", text });
  blocks.push({ type: "list", ordered: false, items: copy.whyList });

  blocks.push({ type: "heading", level: 2, text: copy.noSpotsHeading });
  for (const text of copy.noSpots) blocks.push({ type: "paragraph", text });

  blocks.push({ type: "heading", level: 2, text: copy.safetyHeading });
  for (const text of copy.safety) blocks.push({ type: "paragraph", text });
  blocks.push({
    type: "callout",
    tone: "warning",
    title: copy.safetyCalloutTitle,
    text: copy.safetyCallout,
  });

  blocks.push({ type: "heading", level: 2, text: copy.summaryHeading });
  for (const text of copy.summary) blocks.push({ type: "paragraph", text });

  // This report is the best-ranked page on the site and, until now, it linked
  // to nothing. Everything below is the same trip in the same weeks - chestnut
  // season, the autumn food fairs, the colour of the woods - so the links are
  // editorially right as well as being the only authority this site has to
  // pass on.
  // Local zone pages, when any exist. The registry is empty today, so this
  // adds nothing and renders no empty section: the master gains a "by area"
  // block on the day the first zone is published, and not before.
  const zones = zonesFor(locale);
  if (zones.length > 0) {
    blocks.push({ type: "heading", level: 2, text: ZONES_HEADING[locale] });
    blocks.push({
      type: "list",
      ordered: false,
      items: zones.flatMap((zone) => {
        const href = zoneHref(zone, locale);
        return href ? [`[${zone.areaName}](${href}) — ${zone.comarca}`] : [];
      }),
    });
  }

  blocks.push(...relatedBlocks(["castanyada", "foodfairs", "autumn", "rainy"], locale));

  return blocks;
}

export async function publishMushroomReport(): Promise<PublishResult> {
  const file = IMAGE_BY_KEY.get(HERO.key);

  const spec: ArticleSpec = {
    entryKey: ENTRY_KEY,
    // `article`, not `event`: a weekly condition report, with Article schema.
    type: "article",
    categoryKey: "nature",
    isFeatured: true,
    heroKey: file ? HERO.key : undefined,
    images: file
      ? [
          {
            key: HERO.key,
            url: file.url,
            width: file.width,
            height: file.height,
            blurDataUrl: file.blurDataUrl,
            credit: "CatalunyaInfo",
            license: null,
            alt: HERO.alt,
            caption: HERO.caption,
          },
        ]
      : [],
    sources: SOURCES.map((s) => ({
      name: s.name.ca,
      url: s.url,
      publisher: s.publisher,
      type: "type" in s ? s.type : "official",
    })),
    publishedAt: PUBLISHED,
    lastVerifiedAt: LAST_VERIFIED,
    editions: [],
  };

  // Media rows must exist before the bodies, because image blocks carry a row
  // id. `publishArticle` upserts them, so resolve them first here.
  const { upsertImages } = await import("@/lib/content/publish-article");
  const mediaIds = await upsertImages(spec.images ?? []);
  const heroMediaId = mediaIds.get(HERO.key);

  spec.editions = LOCALES.map((locale) => {
    const copy = COPY[locale];
    return {
      locale,
      path: copy.path,
      title: copy.title,
      excerpt: copy.excerpt,
      seoTitle: copy.seoTitle,
      seoDescription: copy.seoDescription,
      body: buildBody(locale, heroMediaId),
    };
  });

  return publishArticle(spec);
}
